Update functional-tests task for MQ
Signed-off-by: hollisc <hollisc@ca.ibm.com>

diff --git a/mq/environments/ci/tasks/12-functional-tests.yaml b/mq/environments/ci/tasks/12-functional-tests.yaml
--- a/mq/environments/ci/tasks/12-functional-tests.yaml
+++ b/mq/environments/ci/tasks/12-functional-tests.yaml
@@ -61,50 +61,50 @@ spec:
       set -x
       cd $(params.source-dir)
       git checkout $(params.git-revision)
-  - name: wait-till-deployment
-    image: quay.io/openshift/origin-cli:latest
-    workingDir: $(params.source-dir)
-    script: |
-      set -e
-      SLEEP_TIME_SEC=10
-      RETRIES=20
+  # - name: wait-till-deployment
+  #   image: quay.io/openshift/origin-cli:latest
+  #   workingDir: $(params.source-dir)
+  #   script: |
+  #     set -e
+  #     SLEEP_TIME_SEC=10
+  #     RETRIES=20
 
-      SRC_ENV=$(echo $(params.src-environment) | cut -d "-" -f2)
+  #     SRC_ENV=$(echo $(params.src-environment) | cut -d "-" -f2)
 
-      wait_until() {
-        condition=$1
-        message=$2
-        retries=$RETRIES
-        until $condition || [[ "$retries" -eq 0 ]]; do
-          retries=$((retries - 1))
-          sleep $SLEEP_TIME_SEC
-        done
-        if [[ "$retries" -eq 0 ]]; then
-          echo $message
-          exit 1
-        fi
-      }
+  #     wait_until() {
+  #       condition=$1
+  #       message=$2
+  #       retries=$RETRIES
+  #       until $condition || [[ "$retries" -eq 0 ]]; do
+  #         retries=$((retries - 1))
+  #         sleep $SLEEP_TIME_SEC
+  #       done
+  #       if [[ "$retries" -eq 0 ]]; then
+  #         echo $message
+  #         exit 1
+  #       fi
+  #     }
 
-      resolve_deployment() {
-          deployment=$(oc -n ${SRC_ENV} get deploy -l app.kubernetes.io/instance=$(params.release-name) -o jsonpath='{$.items[0].metadata.name}' 2>/dev/null)
-      }
+  #     resolve_deployment() {
+  #         deployment=$(oc -n ${SRC_ENV} get deploy -l app.kubernetes.io/instance=$(params.release-name) -o jsonpath='{$.items[0].metadata.name}' 2>/dev/null)
+  #     }
 
-      resolve_statefulset() {
-          statefulset=$(oc -n ${SRC_ENV} get statefulset -l app.kubernetes.io/instance=$(params.release-name) -o jsonpath='{$.items[0].metadata.name}' 2>/dev/null)
-      }
+  #     resolve_statefulset() {
+  #         statefulset=$(oc -n ${SRC_ENV} get statefulset -l app.kubernetes.io/instance=$(params.release-name) -o jsonpath='{$.items[0].metadata.name}' 2>/dev/null)
+  #     }
 
-      if [[ $(params.instance-type) = "statefulset" ]]; then
-        oc -n ${SRC_ENV} get statefulset
-        wait_until resolve_statefulset "Could not find statefulset"
-        oc -n ${SRC_ENV} rollout status statefulset $statefulset
-      elif [[ $(params.instance-type) = "deployment" ]]; then
-        oc -n ${SRC_ENV} get deploy
-        wait_until resolve_deployment "Could not find deployment"
-        oc -n ${SRC_ENV} rollout status deployment $deployment
-      else
-        echo "App you are looking for does not exist"
-        exit 1
-      fi
+  #     if [[ $(params.instance-type) = "statefulset" ]]; then
+  #       oc -n ${SRC_ENV} get statefulset
+  #       wait_until resolve_statefulset "Could not find statefulset"
+  #       oc -n ${SRC_ENV} rollout status statefulset $statefulset
+  #     elif [[ $(params.instance-type) = "deployment" ]]; then
+  #       oc -n ${SRC_ENV} get deploy
+  #       wait_until resolve_deployment "Could not find deployment"
+  #       oc -n ${SRC_ENV} rollout status deployment $deployment
+  #     else
+  #       echo "App you are looking for does not exist"
+  #       exit 1
+  #     fi
   - name: resolve-route
     image: quay.io/openshift/origin-cli:latest
     workingDir: $(params.source-dir)
